ACTION_IF MOD_IS_INSTALLED "bggo.tp2" (ID_OF_LABEL "bggo.tp2" "baldurs_gate_graphical_overhaul" ) BEGIN

	////////////////////////////////////////////
	// BS0110.are
	////////////////////////////////////////////
	
	COPY_EXISTING ~bs0110.are~ ~override~
		// trigger to leave to BG1300
		LPF fj_are_structure
		INT_VAR
		fj_type         = 2    //travel
		fj_box_left     = 100
		fj_box_top      = 547
		fj_box_right    = 168
		fj_box_bottom   = 643
		fj_cursor_idx   = 42
		fj_vertex_0     = 102 + (547 << 16)
		fj_vertex_1     = 100 + (610 << 16)
		fj_vertex_2     = 168 + (643 << 16)
		fj_vertex_3     = 168 + (575 << 16)
		fj_flags        = BIT2 + BIT8  //full party required, autosave
		STR_VAR
		fj_structure_type   = region
		fj_name             = travar1300
		fj_destination_area = EVAL ~%SEBaldursGate%~
		fj_destination_name = bggo_Door01_exit
		END
	
		
		// BS0110.BCS
		SPRINT area_name_house 	~BS0110~
		SPRINT area_name_1 		EVAL ~%BaldursGateDocks%~
		SPRINT area_name_2 		EVAL ~%SEBaldursGate%~
		
		GET_OFFSET_ARRAY triggers ARE_V10_REGIONS
		PHP_EACH triggers AS i => off BEGIN
			READ_ASCII off triggername (32) NULL
			READ_ASCII off + 0x38 destination
			PATCH_IF ~%destination%~ STR_EQ ~%area_name_1%~ BEGIN
				SPRINT trigger_name_1 ~%triggername%~
			END
			PATCH_IF ~%destination%~ STR_EQ ~%area_name_2%~ BEGIN
				SPRINT trigger_name_2 ~%triggername%~
			END
		END
	<<<<<<<< .../%MOD_FOLDER%/inlinedAreaScriptTriggerActivation.baf
	IF
		Global("%area_name_house%_entered","%area_name_1%",1)
	THEN
		RESPONSE #100
		TriggerActivation("%trigger_name_1%",1)
		TriggerActivation("%trigger_name_2%",0)
		SetGlobal("%area_name_house%_entered","%area_name_2%",0)
	END
	
	IF
		Global("%area_name_house%_entered","%area_name_2%",1)
	THEN
		RESPONSE #100
		TriggerActivation("%trigger_name_1%",0)
		TriggerActivation("%trigger_name_2%",1)
		SetGlobal("%area_name_house%_entered","%area_name_1%",0)
	END
	>>>>>>>> 	
	
	ACTION_IF FILE_EXISTS_IN_GAME ~%area_name_house%.bcs~ BEGIN
		EXTEND_BOTTOM ~%area_name_house%.bcs~ ~.../%MOD_FOLDER%/inlinedAreaScriptTriggerActivation.baf~ EVAL
	END ELSE BEGIN
		COPY ~.../%MOD_FOLDER%/inlinedAreaScriptTriggerActivation.baf~ ~%workspace%/bif/temp/%area_name_house%.baf~
		COMPILE EVAL ~%workspace%/bif/temp/%area_name_house%.baf~
	END
	
	////////////////////////////////////////////
	// BG1200.are BaldursGateDocks
	////////////////////////////////////////////
	
	// travel trigger script
	COPY_EXISTING ~dest01xx.bcs~ ~override~
		DECOMPILE_AND_PATCH BEGIN
			REPLACE_TEXTUALLY ~BG01xx~ ~BS0110~
		END
	
	// delete unused exit
	COPY_EXISTING ~%BaldursGateDocks%.are~ ~override~
		GET_OFFSET_ARRAY entrances ARE_V10_ENTRANCES 
		PHP_EACH entrances AS i => off BEGIN
			READ_ASCII off entrancename (32) NULL
			PATCH_IF ~%entrancename%~ STR_EQ ~exit_bg01xx~ BEGIN
				LPF fj_are_structure
					INT_VAR fj_delete_mode = i
					STR_VAR fj_structure_type = entrance
				END
			END
		END
		// dialog string for Ushers tailor shop
		GET_OFFSET_ARRAY triggers ARE_V10_REGIONS
		PHP_EACH triggers AS i => off BEGIN
			READ_ASCII off triggername (32) NULL
			PATCH_IF ~%triggername%~ STR_EQ ~bsar1200t1~ BEGIN
				READ_LONG off + 0x64 dialog_string
			END
		END
		
		// brazier outside the tailor shop
		PATCH_DEFINE_ARRAY x_coord BEGIN 4313 END
		PATCH_DEFINE_ARRAY y_coord BEGIN 459  END
		PATCH_PHP_EACH x_coord AS index => x BEGIN
			LPF fj_are_structure
			INT_VAR
				fj_loc_x = $x_coord("%index%")
				fj_loc_y = $y_coord("%index%")
				fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
				fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
				STR_VAR
				fj_structure_type = animation
				fj_name = FLAME2N
				fj_bam_resref = FLAME2N //bgrd
			END
		END
		CLEAR_ARRAY x_coord
		CLEAR_ARRAY y_coord
	
	////////////////////////////////////////////
	// BG1300.are SEBaldursGate
	////////////////////////////////////////////
	
	/*
	// travel trigger script
	COPY_EXISTING ~dest01xx.bcs~ ~override~
		DECOMPILE_AND_PATCH BEGIN
			REPLACE_TEXTUALLY ~BG01xx~ ~BS0110~
		END
	*/
	COPY_EXISTING ~%SEBaldursGate%.are~ ~override~
		// change flag for taylor shop door
		GET_OFFSET_ARRAY doors ARE_V10_DOORS
		PHP_EACH doors AS i => off BEGIN
			READ_ASCII off + 0x20 door_id
			PATCH_IF ~%door_id%~ STR_EQ ~door1300~ BEGIN
				WRITE_LONG off + 0x28 BIT1 + BIT6	//BIT1 locked BIT6 is door
				WRITE_LONG off + 0x88 0		// detection difficulty
			END
		END
		
		// change settings for travel trigger to the taylor shop
		GET_OFFSET_ARRAY triggers ARE_V10_REGIONS
		PHP_EACH triggers AS i => off BEGIN
			READ_ASCII off triggername (32) NULL
			PATCH_IF ~%triggername%~ STR_EQ ~bggo_Door01~ BEGIN
				WRITE_ASCII off + 0x38 ~BS0110~		// destination
				WRITE_ASCII off + 0x40 ~exitar1200~ #32	// exit
				WRITE_LONG  off + 0x60 BIT10 + BIT11 // BIT10 activation point BIT11 connected to door
			END
			PATCH_IF ~%triggername%~ STR_EQ ~bggo_InfoHouse~ BEGIN
				WRITE_LONG off + 0x60 (THIS | BIT8) //deactivates
			END
		END
		
		// map note taylor shop		
		LPF fj_are_structure
		INT_VAR
			fj_loc_x = 36
			fj_loc_y = 390
			fj_note_strref = ~%dialog_string%~
		STR_VAR
			fj_structure_type   = note
		END
		
		// brazier outside the tailor shop
		PATCH_DEFINE_ARRAY x_coord BEGIN 36  END
		PATCH_DEFINE_ARRAY y_coord BEGIN 443 END
		PATCH_PHP_EACH x_coord AS index => x BEGIN
			LPF fj_are_structure
			INT_VAR
				fj_loc_x = $x_coord("%index%")
				fj_loc_y = $y_coord("%index%")
				fj_schedule = 0b111000000000000000111111 //Hours 22.00 - 07.00
				fj_flags = 0b00000000000000000001000001100011	// Visible, blend colours, not covered by wall, don't remove in combat
				STR_VAR
				fj_structure_type = animation
				fj_name = FLAME2N
				fj_bam_resref = FLAME2N //bgrd
			END
		END
		CLEAR_ARRAY x_coord
		CLEAR_ARRAY y_coord
		
		// door script for info text when the door is clicked
		<<<<<<<< .../%MOD_FOLDER%/inlined_door_script.baf
		IF
			Global("BGGO_opened_BG01XX","GLOBAL",1)
		THEN
			RESPONSE #100
				SetGlobal("BGGO_trigger_text","MYAREA",1)
				Unlock("door01")
		END
		IF
			Global("BGGO_trigger_text","MYAREA",0)
			Clicked([ANYONE])
			OpenState("door01",FALSE)
		THEN
			RESPONSE #100
				DisplayString("door01",%dialog_string%)
				SetGlobal("BGGO_trigger_text","MYAREA",1)
				Unlock("door01")
		END
		>>>>>>>>
	
	EXTEND_BOTTOM ~dr01XX13.bcs~ ~.../%MOD_FOLDER%/inlined_door_script.baf~ EVAL
END

